"use strict";
const RULES={maxHp:100,damage:{head:25,waist:20,legs:15},counter:10};
const ACTIONS={"attack-head":["attack","head","head"],"attack-waist":["attack","waist","waist"],"attack-legs":["attack","legs","legs"],"defend-upper":["defend","upper","defense"]};
const ZONE={head:"頭",waist:"腰",legs:"足"};
const ASSETS={background:"assets/pool-background.png",haku:{idle:"assets/haku-idle.png",head:"assets/haku-head.png",waist:"assets/haku-waist.png",legs:"assets/haku-legs.png",defense:"assets/haku-defense.png",fall:"assets/haku-fall.png"},yuya:{idle:"assets/yuya-idle.png",head:"assets/yuya-head.png",waist:"assets/yuya-waist.png",legs:"assets/yuya-legs.png",defense:"assets/yuya-defense.png",fall:"assets/yuya-fall.png"}};

class GameState{constructor(){this.reset()}reset(){this.hp={haku:100,yuya:100};this.round=1;this.chooser="haku";this.choices={};this.visual={haku:"idle",yuya:"idle"};this.finished=false;this.animating=false;this.motionStart=performance.now()}}

class BattleRules{static resolve(a,b){const damage={haku:0,yuya:0},notes=[];if(a[0]==="attack"&&b[0]==="attack"&&a[1]===b[1])return{damage,notes:[`同じ${ZONE[a[1]]}を攻撃。引き分けでダメージなし！`]};this.one("haku",a,"yuya",b,damage,notes);this.one("yuya",b,"haku",a,damage,notes);if(!notes.length)notes.push("お互いに防御。ダメージなし。");return{damage,notes}}static one(attacker,a,target,b,d,n){if(a[0]!=="attack")return;const an=attacker==="haku"?"ハク":"ゆや",tn=target==="haku"?"ハク":"ゆや",zone=ZONE[a[1]];if(b[0]==="defend"&&(a[1]==="head"||a[1]==="waist")){d[attacker]+=RULES.counter;n.push(`${tn}が頭と腰を防御！ ${an}に反撃10ダメージ。`)}else{const amount=RULES.damage[a[1]];d[target]+=amount;n.push(`${an}の${zone}攻撃！ ${tn}に${amount}ダメージ。${a[1]==="legs"&&b[0]==="defend"?"（足は防御不能）":""}`)}}}

class Renderer{
  constructor(canvas,state){this.canvas=canvas;this.c=canvas.getContext("2d");this.state=state;this.images={};this.load();this.loop()}
  load(){const paths={background:ASSETS.background};for(const id of ["haku","yuya"])for(const pose of Object.keys(ASSETS[id]))paths[`${id}-${pose}`]=ASSETS[id][pose];for(const [key,path] of Object.entries(paths)){const image=new Image;image.onload=()=>this.draw();image.src=path;this.images[key]=image}}
  loop(){this.draw();requestAnimationFrame(()=>this.loop())}
  draw(){const c=this.c,w=this.canvas.width,h=this.canvas.height,t=performance.now()-this.state.motionStart;c.clearRect(0,0,w,h);this.cover(this.images.background,0,0,w,h);this.platform(w*.285,h*.82,"#ffd83f");this.platform(w*.715,h*.82,"#ba82f1");this.sprite("haku",w*.285,h*.81,w*.38,h*.72,t);this.sprite("yuya",w*.715,h*.81,w*.38,h*.72,t);if(this.state.animating&&!this.state.finished&&t<900)this.impact(w/2,h*.46,t)}
  cover(image,x,y,w,h){if(!image?.complete||!image.naturalWidth){this.c.fillStyle="#1687c5";this.c.fillRect(x,y,w,h);return}const scale=Math.max(w/image.naturalWidth,h/image.naturalHeight),sw=w/scale,sh=h/scale;this.c.drawImage(image,(image.naturalWidth-sw)/2,(image.naturalHeight-sh)/2,sw,sh,x,y,w,h)}
  platform(x,y,color){const c=this.c,w=this.canvas.width*.29,h=this.canvas.height*.085;c.fillStyle=color+"cc";c.beginPath();c.ellipse(x,y,w/2,h/2,0,0,Math.PI*2);c.fill();c.strokeStyle="#fff9";c.lineWidth=3;c.stroke()}
  sprite(id,x,bottom,maxW,maxH,t){let pose=this.state.visual[id];if(this.state.finished&&this.state.hp[id]<=0)pose="fall";const image=this.images[`${id}-${pose}`];if(!image?.complete||!image.naturalWidth)return;const direction=id==="haku"?1:-1;let dx=0,dy=0,rotation=0;if(this.state.finished&&pose==="fall"){dy=Math.min(t/6,150);rotation=direction*Math.min(t/2200,.35)}else if(this.state.animating){const wave=Math.sin(Math.min(t,900)/900*Math.PI);if(pose==="head"||pose==="waist"||pose==="legs")dx=direction*55*wave;if(pose==="defense")dx=direction*12*wave}else{dy=Math.sin(performance.now()/500+(id==="haku"?0:1))*3}const scale=Math.min(maxW/image.naturalWidth,maxH/image.naturalHeight),w=image.naturalWidth*scale,h=image.naturalHeight*scale;this.c.save();this.c.translate(x+dx,bottom+dy);this.c.rotate(rotation);this.c.drawImage(image,-w/2,-h,w,h);this.c.restore()}
  impact(x,y,t){const p=Math.sin(Math.min(t,700)/700*Math.PI),c=this.c;c.save();c.translate(x,y);c.fillStyle=`rgba(255,255,255,${p*.9})`;c.shadowColor="#ff8df4";c.shadowBlur=45*p;c.beginPath();for(let i=0;i<16;i++){const a=i/16*Math.PI*2,r=i%2?18*p:65*p;c.lineTo(Math.cos(a)*r,Math.sin(a)*r)}c.closePath();c.fill();c.restore()}
}

class NetworkAdapter{async connect(){throw Error("オンライン対戦は次の段階です")}}

class GameController{
  constructor(){
    this.mode="cpu";this.cpuThinking=false;this.room=null;this.onlineReady=false;this.onlineData=null;this.onlineSubmitted=false;this.lastApplied=0;this.resolvingRound=0;
    this.s=new GameState;this.r=new Renderer(document.querySelector("#game"),this.s);
    this.ui={guide:document.querySelector("#guide"),ready:document.querySelector("#ready"),log:document.querySelector("#log"),round:document.querySelector("#round"),finish:document.querySelector("#finish"),winner:document.querySelector("#winner"),actions:document.querySelector("#actions"),modes:document.querySelector("#mode-select"),lobby:document.querySelector("#room-lobby"),roomStart:document.querySelector("#room-start"),roomCreated:document.querySelector("#room-created"),roomCode:document.querySelector("#room-code"),roomInput:document.querySelector("#room-code-input"),roomStatus:document.querySelector("#room-status"),roomRole:document.querySelector("#room-role"),roomState:document.querySelector("#room-state")};
    this.ui.actions.onclick=e=>{const b=e.target.closest("[data-action]");if(b)this.choose(b.dataset.action)};this.ui.modes.onclick=e=>{const b=e.target.closest("[data-mode]");if(b)this.changeMode(b.dataset.mode)};document.querySelector("#create-room").onclick=()=>this.createRoom();document.querySelector("#join-room").onclick=()=>this.joinRoom();document.querySelector("#copy-room").onclick=()=>this.copyRoom();document.querySelector("#restart").onclick=()=>this.restart();
    window.addEventListener("firebase-battle-ready",()=>{this.onlineReady=true;this.ui.log.textContent="Firebase通信の準備ができました";this.update()});
    window.addEventListener("firebase-battle-error",e=>{this.ui.log.textContent=e.detail.message;this.ui.roomStatus.textContent=e.detail.message});
    window.addEventListener("firebase-battle-room",e=>this.onOnlineRoom(e.detail));
    window.addEventListener("firebase-battle-moves",e=>this.onOnlineMoves(e.detail.moves));
    this.update();
  }
  changeMode(mode){if(!["cpu","local","online"].includes(mode)||this.s.animating)return;this.mode=mode;this.ui.lobby.hidden=mode!=="online";this.restart();this.ui.log.textContent=mode==="cpu"?"CPU対戦を開始します。あなたはハクです。":mode==="local"?"1台で2人対戦を開始します。":"部屋を作るか、部屋番号を入力してください。"}
  makeCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",bytes=new Uint8Array(6);crypto.getRandomValues(bytes);return Array.from(bytes,n=>chars[n%chars.length]).join("")}
  showRoom(code,role){this.room={code,role};this.ui.roomStart.hidden=true;this.ui.roomCreated.hidden=false;this.ui.roomCode.textContent=code;this.ui.roomRole.textContent=role==="host"?"あなたは ハク（部屋主）":"あなたは ゆや（参加者）";this.ui.roomState.textContent=role==="host"?"✓ 部屋作成・通信開始":"✓ 部屋参加・通信開始";this.ui.roomStatus.textContent=role==="host"?"ゆやの参加を待っています":"ハクとの接続を確認しています";location.hash=`room=${code}`;this.update()}
  async createRoom(){if(!this.onlineReady){this.ui.log.textContent="Firebase接続の準備中です";return}const code=this.makeCode();try{await window.firebaseBattle.createRoom(code);this.showRoom(code,"host")}catch(e){this.ui.log.textContent=e.message}}
  async joinRoom(){const code=this.ui.roomInput.value.trim().toUpperCase();if(!/^[A-Z2-9]{6}$/.test(code)){this.ui.log.textContent="部屋番号は英数字6桁で入力してください。";return}try{await window.firebaseBattle.joinRoom(code);this.showRoom(code,"guest")}catch(e){this.ui.log.textContent=e.message}}
  async copyRoom(){if(!this.room)return;try{await navigator.clipboard.writeText(this.room.code);this.ui.roomStatus.textContent="部屋番号をコピーしました"}catch{this.ui.roomStatus.textContent=`部屋番号：${this.room.code}`}}
  choose(key){if(this.s.finished||this.s.animating||this.cpuThinking||!ACTIONS[key])return;if(this.mode==="online"){this.onlineChoose(key);return}this.s.choices[this.s.chooser]=ACTIONS[key];if(this.s.chooser==="haku"){this.s.chooser="yuya";if(this.mode==="cpu"){this.cpuThinking=true;this.ui.log.textContent="CPUゆやが行動を考えています…";this.update();setTimeout(()=>this.cpuChoose(),650);return}this.ui.log.textContent="ハクの行動を記録しました。画面をゆやに渡してください。"}else this.resolve();this.update()}
  async onlineChoose(key){if(!this.room||!this.onlineData?.guestUid||this.onlineSubmitted)return;const role=this.room.role==="host"?"haku":"yuya";this.onlineSubmitted=true;this.s.visual[role]=ACTIONS[key][2];this.ui.log.textContent="行動を送信しました。相手を待っています…";this.update();try{await window.firebaseBattle.submitMove(this.room.code,role,key,this.s.round)}catch(e){this.onlineSubmitted=false;this.ui.log.textContent=e.message;this.update()}}
  onOnlineRoom(data){if(!this.room||data.code!==this.room.code)return;this.onlineData=data;if(data.status==="playing"&&!data.lastResult&&this.s.finished){this.s.reset();this.lastApplied=0;this.onlineSubmitted=false;this.ui.finish.hidden=true}this.s.hp.haku=data.hakuHp;this.s.hp.yuya=data.yuyaHp;this.s.round=data.round;if(data.guestUid){this.ui.roomState.textContent="✓ 2台の接続完了";this.ui.roomStatus.textContent="ハクとゆやが接続しました。行動を選んでください"}if(data.lastResult&&data.lastResult.round>this.lastApplied)this.applyOnlineResult(data);this.update()}
  async onOnlineMoves(moves){if(this.mode!=="online"||this.room?.role!=="host"||!moves.haku||!moves.yuya||moves.haku.round!==moves.yuya.round||moves.haku.round!==this.s.round||this.resolvingRound===this.s.round)return;this.resolvingRound=this.s.round;const a=ACTIONS[moves.haku.action],b=ACTIONS[moves.yuya.action],result=BattleRules.resolve(a,b),h=Math.max(0,this.s.hp.haku-result.damage.haku),y=Math.max(0,this.s.hp.yuya-result.damage.yuya),finished=!h||!y;try{await window.firebaseBattle.publishResult(this.room.code,{hakuHp:h,yuyaHp:y,round:finished?this.s.round:this.s.round+1,status:finished?"finished":"playing",lastResult:{round:this.s.round,hakuAction:moves.haku.action,yuyaAction:moves.yuya.action,notes:result.notes}})}catch(e){this.resolvingRound=0;this.ui.log.textContent=e.message}}
  applyOnlineResult(data){const result=data.lastResult;this.lastApplied=result.round;this.onlineSubmitted=false;this.resolvingRound=0;this.s.animating=true;this.s.motionStart=performance.now();this.s.visual.haku=ACTIONS[result.hakuAction][2];this.s.visual.yuya=ACTIONS[result.yuyaAction][2];this.ui.log.textContent=`第${result.round}ラウンド：${result.notes.join(" ")}`;if(data.status==="finished"){this.s.finished=true;this.s.motionStart=performance.now();this.ui.winner.textContent=!data.hakuHp&&!data.yuyaHp?"両者、水へ！ 引き分け":!data.hakuHp?"ゆやの勝ち！":"ハクの勝ち！";setTimeout(()=>this.ui.finish.hidden=false,1300)}else setTimeout(()=>{this.s.visual={haku:"idle",yuya:"idle"};this.s.animating=false;this.s.motionStart=performance.now();this.update()},1100)}
  cpuChoose(){if(this.s.finished||this.mode!=="cpu")return;const key=this.cpuAction();this.s.choices.yuya=ACTIONS[key];this.cpuThinking=false;this.resolve();this.update()}
  cpuAction(){const low=this.s.hp.yuya<=40,choices=low?["defend-upper","defend-upper","defend-upper","attack-head","attack-waist","attack-legs"]:["defend-upper","attack-head","attack-head","attack-waist","attack-waist","attack-legs","attack-legs"];return choices[Math.floor(Math.random()*choices.length)]}
  resolve(){this.s.animating=true;this.s.motionStart=performance.now();this.s.visual.haku=this.s.choices.haku[2];this.s.visual.yuya=this.s.choices.yuya[2];const result=BattleRules.resolve(this.s.choices.haku,this.s.choices.yuya);for(const id of ["haku","yuya"])this.s.hp[id]=Math.max(0,this.s.hp[id]-result.damage[id]);this.ui.log.textContent=`第${this.s.round}ラウンド：${result.notes.join(" ")}`;this.s.choices={};if(!this.s.hp.haku||!this.s.hp.yuya){this.s.finished=true;this.s.motionStart=performance.now();const h=this.s.hp.haku,y=this.s.hp.yuya;this.ui.winner.textContent=!h&&!y?"両者、水へ！ 引き分け":!h?"ゆやの勝ち！":"ハクの勝ち！";setTimeout(()=>this.ui.finish.hidden=false,1300)}else{this.s.round++;this.s.chooser="haku";setTimeout(()=>{this.s.visual={haku:"idle",yuya:"idle"};this.s.animating=false;this.s.motionStart=performance.now();this.update()},1100)}}
  restart(){if(this.mode==="online"&&this.room){if(this.room.role==="host"){this.ui.log.textContent="再戦を準備しています…";window.firebaseBattle.resetRoom(this.room.code).catch(e=>this.ui.log.textContent=e.message)}else this.ui.log.textContent="部屋主が再戦を開始するのを待ってください";return}this.cpuThinking=false;this.onlineSubmitted=false;this.s.reset();this.ui.finish.hidden=true;this.ui.log.textContent=this.mode==="cpu"?"CPUゆやに勝利してください！":this.mode==="local"?"お互いの行動は、両者が選び終わるまで秘密です。":"部屋を作るか、部屋番号を入力してください。";this.update()}
  update(){for(const id of ["haku","yuya"]){document.querySelector(`#${id}Hp`).value=this.s.hp[id];document.querySelector(`#${id}Text`).textContent=`HP ${this.s.hp[id]}`}this.ui.round.textContent=`ROUND ${this.s.round}`;const online=this.mode==="online",connected=online&&this.onlineData?.guestUid;this.ui.guide.textContent=online?this.room?connected?this.onlineSubmitted?"相手の行動を待っています":`${this.room.role==="host"?"ハク":"ゆや"}の行動を選んでください`:`部屋 ${this.room.code}：参加待ち`:"オンライン対戦の準備":this.s.finished?"バトル終了":this.s.animating?"攻撃中！":this.cpuThinking?"CPUゆやが考えています…":`${this.s.chooser==="haku"?"ハク":"ゆや"}の行動を選んでください`;this.ui.ready.textContent=online?this.room?connected?`あなた：${this.room.role==="host"?"ハク":"ゆや"} ／ 2台接続済み`:"相手を待っています":"部屋未参加":this.s.animating?"両者の行動を実行中":this.mode==="cpu"?`ハク：${this.s.chooser==="haku"?"選択中":"選択済み"} ／ CPUゆや：${this.cpuThinking?"思考中":"待機中"}`:`ハク：${this.s.choices.haku?"選択済み":this.s.chooser==="haku"?"選択中":"待機中"} ／ ゆや：${this.s.chooser==="yuya"?"選択中":"待機中"}`;this.ui.actions.querySelectorAll("button").forEach(b=>b.disabled=online?(!connected||this.onlineSubmitted||this.s.animating||this.s.finished):(this.s.animating||this.s.finished||this.cpuThinking));this.ui.modes.querySelectorAll("button").forEach(b=>{b.style.opacity=b.dataset.mode===this.mode?"1":".5";b.disabled=this.s.animating||this.cpuThinking});this.r.draw()}
}
new GameController;
